#encoding: utf-8
# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
Pais.create(:id => 1, :nome => "Alemanha")
Pais.create(:id => 2, :nome => "America")
Pais.create(:id => 3, :nome => "do")
Pais.create(:id => 4, :nome => "Sul")
Pais.create(:id => 5, :nome => "Argélia")
Pais.create(:id => 6, :nome => "Argentina")
Pais.create(:id => 7, :nome => "Austrália")
Pais.create(:id => 8, :nome => "Áustria")
Pais.create(:id => 9, :nome => "Bélgica")
Pais.create(:id => 10, :nome => "Brasil")
Pais.create(:id => 11, :nome => "Canadá")
Pais.create(:id => 12, :nome => "Chile")
Pais.create(:id => 13, :nome => "China")
Pais.create(:id => 14, :nome => "Coréia")
Pais.create(:id => 15, :nome => "do")
Pais.create(:id => 16, :nome => "Sul")
Pais.create(:id => 17, :nome => "Cuba")
Pais.create(:id => 18, :nome => "Dinamarca")
Pais.create(:id => 19, :nome => "Eslovênia")
Pais.create(:id => 20, :nome => "Espanha")
Pais.create(:id => 21, :nome => "EUA")
Pais.create(:id => 22, :nome => "Europa")
Pais.create(:id => 23, :nome => "Finlândia")
Pais.create(:id => 24, :nome => "França")
Pais.create(:id => 25, :nome => "Geórgia")
Pais.create(:id => 26, :nome => "Grécia")
Pais.create(:id => 27, :nome => "Holanda")
Pais.create(:id => 28, :nome => "Hong")
Pais.create(:id => 29, :nome => "Kong")
Pais.create(:id => 30, :nome => "Hungria")
Pais.create(:id => 31, :nome => "Inglaterra")
Pais.create(:id => 32, :nome => "Irã")
Pais.create(:id => 33, :nome => "Irlanda")
Pais.create(:id => 34, :nome => "Israel")
Pais.create(:id => 35, :nome => "Itália")
Pais.create(:id => 36, :nome => "Iugoslávia")
Pais.create(:id => 37, :nome => "Jamaica")
Pais.create(:id => 38, :nome => "Japão")
Pais.create(:id => 39, :nome => "Macedônia")
Pais.create(:id => 40, :nome => "México")
Pais.create(:id => 41, :nome => "Nova")
Pais.create(:id => 42, :nome => "Zelândia")
Pais.create(:id => 43, :nome => "Palestina")
Pais.create(:id => 44, :nome => "Polônia")
Pais.create(:id => 45, :nome => "Reino")
Pais.create(:id => 46, :nome => "Unido")
Pais.create(:id => 47, :nome => "República")
Pais.create(:id => 48, :nome => "Tcheca")
Pais.create(:id => 49, :nome => "Rino")
Pais.create(:id => 50, :nome => "Unido")
Pais.create(:id => 51, :nome => "Ruanda")
Pais.create(:id => 52, :nome => "Russia")
Pais.create(:id => 53, :nome => "Suécia")
Pais.create(:id => 54, :nome => "Taiwan")
Pais.create(:id => 55, :nome => "Turquia")
Pais.create(:id => 56, :nome => "URSS")
Pais.create(:id => 57, :nome => "Uruguai")
Pais.create(:id => 58, :nome => "Vietnam")

Midia.create(:id => 1, :nome => "Blu-Ray")
Midia.create(:id => 2, :nome => "Brasil")
Midia.create(:id => 3, :nome => "Cinema")
Midia.create(:id => 4, :nome => "Download")
Midia.create(:id => 5, :nome => "DVD")
Midia.create(:id => 6, :nome => "FX")
Midia.create(:id => 7, :nome => "HBO")
Midia.create(:id => 8, :nome => "INT")
Midia.create(:id => 9, :nome => "MGM")
Midia.create(:id => 10, :nome => "Space")
Midia.create(:id => 11, :nome => "TCM")
Midia.create(:id => 12, :nome => "Telecine")
Midia.create(:id => 13, :nome => "TNT")
Midia.create(:id => 14, :nome => "TV")
Midia.create(:id => 15, :nome => "TVA")
Midia.create(:id => 16, :nome => "TVC")
Midia.create(:id => 17, :nome => "Universal")
Midia.create(:id => 18, :nome => "Vídeo")
Midia.create(:id => 19, :nome => "Warner")

Genero.create(:id => 1, :nome => "Ação")
Genero.create(:id => 2, :nome => "Animação")
Genero.create(:id => 3, :nome => "Arte")
Genero.create(:id => 4, :nome => "Aventura")
Genero.create(:id => 5, :nome => "Biografia")
Genero.create(:id => 6, :nome => "Comédia")
Genero.create(:id => 7, :nome => "Crime")
Genero.create(:id => 8, :nome => "Documentário")
Genero.create(:id => 9, :nome => "Drama")
Genero.create(:id => 10, :nome => "Épico")
Genero.create(:id => 11, :nome => "Erótico")
Genero.create(:id => 12, :nome => "Espionagem")
Genero.create(:id => 13, :nome => "Fantasia")
Genero.create(:id => 14, :nome => "Ficção")
Genero.create(:id => 15, :nome => "Gangster")
Genero.create(:id => 16, :nome => "Guerra")
Genero.create(:id => 17, :nome => "História")
Genero.create(:id => 18, :nome => "Mistério")
Genero.create(:id => 19, :nome => "Musical")
Genero.create(:id => 20, :nome => "Policial")
Genero.create(:id => 21, :nome => "Político")
Genero.create(:id => 22, :nome => "Pornô")
Genero.create(:id => 23, :nome => "Romance")
Genero.create(:id => 24, :nome => "Suspense")
Genero.create(:id => 25, :nome => "Terror")
Genero.create(:id => 26, :nome => "Tribunal")
Genero.create(:id => 27, :nome => "Western")

Ator.create(:id => 1, :nome => "Eric Bana", :sexo => "1")
Ator.create(:id => 2, :nome => "Jennifer Connelly", :sexo => "2")
Ator.create(:id => 3, :nome => "Nick Nolte", :sexo => "1")

Diretor.create(:id => 1, :nome => "Bryan Singer")
Diretor.create(:id => 2, :nome => "John Frankenheimer")
Diretor.create(:id => 3, :nome => "Quentin Tarantino")

Roteirista.create(:id => 1, :nome => "Nick Cave")
Roteirista.create(:id => 2, :nome => "Jonathan Nolan")
Roteirista.create(:id => 3, :nome => "Neal Purvis")
